Reading the file

In [1]:
import pandas as pd
df = pd.read_csv('../Data/SBAnational.csv',on_bad_lines='skip')

C:\Users\Akhil M\AppData\Local\Temp\ipykernel_19844\2538448538.py:2: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../Data/SBAnational.csv',on_bad_lines='skip')

In [2]:
df.describe()

,LoanNr_ChkDgt,Zip,NAICS,Term,NoEmp,NewExist,CreateJob,RetainedJob,FranchiseCode,UrbanRural
count,8.991640e+05,899164.000000,899164.000000,899164.000000,899164.000000,899028.000000,899164.000000,899164.000000,899164.000000,899164.000000
mean,4.772612e+09,53804.391241,398660.950146,110.773078,11.411353,1.280404,8.430376,10.797257,2753.725933,0.757748
std,2.538175e+09,31184.159152,263318.312760,78.857305,74.108196,0.451750,236.688165,237.120600,12758.019136,0.646436
min,1.000014e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.589758e+09,27587.000000,235210.000000,60.000000,2.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,4.361439e+09,55410.000000,445310.000000,84.000000,4.000000,1.000000,0.000000,1.000000,1.000000,1.000000
75%,6.904627e+09,83704.000000,561730.000000,120.000000,10.000000,2.000000,1.000000,4.000000,1.000000,1.000000
max,9.996003e+09,99999.000000,928120.000000,569.000000,9999.000000,2.000000,8800.000000,9500.000000,99999.000000,2.000000

In [3]:
df.info(verbose=True,show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 899164 entries, 0 to 899163
Data columns (total 27 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   LoanNr_ChkDgt      899164 non-null  int64
 1   Name               899150 non-null  object
 2   City               899134 non-null  object
 3   State              899150 non-null  object
 4   Zip                899164 non-null  int64
 5   Bank               897605 non-null  object
 6   BankState          897598 non-null  object
 7   NAICS              899164 non-null  int64
 8   ApprovalDate       899164 non-null  object
 9   ApprovalFY         899164 non-null  object
 10  Term               899164 non-null  int64
 11  NoEmp              899164 non-null  int64
 12  NewExist           899028 non-null  float64
 13  CreateJob          899164 non-null  int64
 14  RetainedJob        899164 non-null  int64
 15  FranchiseCode      899164 non-null  int64
 16  UrbanRural         899164 non-null  int64
 17  RevLineCr          894636 non-null  object
 18  LowDoc             896582 non-null  object
 19  ChgOffDate         162699 non-null  object
 20  DisbursementDate   896796 non-null  object
 21  DisbursementGross  899164 non-null  object
 22  BalanceGross       899164 non-null  object
 23  MIS_Status         897167 non-null  object
 24  ChgOffPrinGr       899164 non-null  object
 25  GrAppv             899164 non-null  object
 26  SBA_Appv           899164 non-null  object
dtypes: float64(1), int64(9), object(17)
memory usage: 185.2+ MB

In [4]:
df.sample(5)

,LoanNr_ChkDgt,Name,City,State,Zip,Bank,BankState,NAICS,ApprovalDate,ApprovalFY,...,RevLineCr,LowDoc,ChgOffDate,DisbursementDate,DisbursementGross,BalanceGross,MIS_Status,ChgOffPrinGr,GrAppv,SBA_Appv
676246,6940214007,A & C TODD CO LLC,COLUMBUS,OH,43229,U.S. BANK NATIONAL ASSOCIATION,OH,238350,19-Nov-03,2004,...,0,N,NaN,31-Dec-03,"$20,000.00",$0.00,P I F,$0.00,"$20,000.00","$10,000.00"
258408,2812646007,DESERT EAGLE FIRE PROTECTION L,SURPRISE,AZ,85379,COMPASS BANK,AL,238990,24-May-07,2007,...,Y,N,23-May-11,30-Sep-07,"$27,176.00",$0.00,CHGOFF,"$6,692.00","$10,000.00","$5,000.00"
210412,2485705007,BEAU JAMES BILBRO DBA 24 HOUR,PLEASANT GROVE,UT,84062,CAPITAL ONE NATL ASSOC,VA,492110,31-May-07,2007,...,N,N,NaN,30-Jun-07,"$35,000.00",$0.00,P I F,$0.00,"$50,000.00","$25,000.00"
766850,8061783010,"ZUTANO, INC",CABOT,VT,5647,CHITTENDEN TR COMPANY A DIVISI,VT,422330,8-Feb-95,1995,...,N,N,NaN,30-Apr-95,"$200,000.00",$0.00,P I F,$0.00,"$200,000.00","$150,000.00"
688662,7132514010,TYRY MANAGEMENT INC,ROCKLIN,CA,95677,BANK OF THE WEST,CA,311423,29-Jan-04,2004,...,0,N,NaN,29-Feb-04,"$350,000.00",$0.00,P I F,$0.00,"$350,000.00","$262,500.00"

In [5]:
df.isnull().mean().sort_values(ascending=False)

ChgOffDate           0.819055
RevLineCr            0.005036
LowDoc               0.002872
DisbursementDate     0.002634
MIS_Status           0.002221
BankState            0.001742
Bank                 0.001734
NewExist             0.000151
City                 0.000033
State                0.000016
Name                 0.000016
Term                 0.000000
ApprovalFY           0.000000
ApprovalDate         0.000000
NAICS                0.000000
Zip                  0.000000
LoanNr_ChkDgt        0.000000
RetainedJob          0.000000
NoEmp                0.000000
FranchiseCode        0.000000
UrbanRural           0.000000
CreateJob            0.000000
DisbursementGross    0.000000
BalanceGross         0.000000
ChgOffPrinGr         0.000000
GrAppv               0.000000
SBA_Appv             0.000000
dtype: float64

In [6]:
df['MIS_Status'].value_counts()

MIS_Status
P I F     739609
CHGOFF    157558
Name: count, dtype: int64

Split as Input and Target

In [7]:
Y=df['MIS_Status']
X=df.drop(columns=['MIS_Status'])

Dropping more columns because they are causing data leakage

In [8]:
X=df.drop(columns=['ChgOffPrinGr','BalanceGross','ChgOffDate'])

Train Test splitting

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

Split your Xtrain data to two different types of categories. Numerical vs Categorical. You further have to split Categorical as Nominal and Ordinal

In [10]:
numCols=list(X_train.select_dtypes(include=['int64','float64']).columns)
catCols=list(X_train.select_dtypes(include=['object']).columns)

In [11]:
type(numCols)

list

Sending correct column to correct array

In [12]:
wrongCat=['DisbursementGross','GrAppv','SBA_Appv']
wrongNum=['NewExist','UrbanRural']

Removing wrong data and appending it correctly to numCols

In [13]:
for col in wrongCat:
    catCols.remove(col)
numCols.extend(wrongCat)

Removing wrong data from numCols and appending it correctly to catCols

In [14]:
for cols in wrongNum:
    numCols.remove(cols)
catCols.extend(wrongNum)

Imputing missing values

In [15]:
df[numCols].isnull().mean().sort_values(ascending=False)

LoanNr_ChkDgt        0.0
Zip                  0.0
NAICS                0.0
Term                 0.0
NoEmp                0.0
CreateJob            0.0
RetainedJob          0.0
FranchiseCode        0.0
DisbursementGross    0.0
GrAppv               0.0
SBA_Appv             0.0
dtype: float64

In [16]:
df[catCols].isnull().mean().sort_values(ascending=False)

RevLineCr           0.005036
LowDoc              0.002872
DisbursementDate    0.002634
MIS_Status          0.002221
BankState           0.001742
Bank                0.001734
NewExist            0.000151
City                0.000033
Name                0.000016
State               0.000016
ApprovalFY          0.000000
ApprovalDate        0.000000
UrbanRural          0.000000
dtype: float64